# Generated by Django 4.1 on 2022-08-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="binance_bitcoin",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="binance_money",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(default="", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="huobi_bitcoin",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="huobi_money",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
