# Generated by Django 4.1 on 2022-08-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="Email",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="users",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="users",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
