# Generated by Django 4.1 on 2022-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_users_email_users_first_name_users_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="bitcoin",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="users",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="users",
            name="Email",
            field=models.EmailField(default="", max_length=255),
        ),
    ]
