# Generated by Django 4.1 on 2022-08-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_users_binance_bitcoin_users_binance_money_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="binance_money",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="huobi_money",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
