# Generated by Django 4.1 on 2022-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0004_rename_email_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
