# Generated by Django 4.1 on 2022-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0005_alter_users_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="bitcoin",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="money",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
