# Generated by Django 4.1 on 2022-08-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0006_alter_users_bitcoin_alter_users_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(default="", max_length=255, unique=True),
        ),
    ]
